
default: &default
  adapter: mysql2
  encoding: utf8mb4 
  pool: 5
  database: app
  username: root
  password: password
  host: db

development:
  <<: *default


test:
  <<: *default


production:
  <<: *default
